version: '3.1'

services:
  web:
    image: alerta/alerta-apnm-web:8.7.0
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      # - DEBUG=1  # remove this line to turn DEBUG off
      - DATABASE_URL=postgres://postgres:postgres@db:5432/monitoring
    restart: always

  db:
    image: postgres
    ports:
      - 5432
    environment:
      POSTGRES_DB: monitoring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
